name: CBIG_An2024
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.1
  - setuptools=52.0.0
  - pip=21.1.3
  - r-matrixstats=0.60.0
  - wheel=0.36.2
  - python=3.9.5
  - r-base=4.1.0
  - pip:
    - numpy==1.21.1
    - pandas==1.1.5
    - scipy==1.9.1
    - rpy2==3.3.6
    - sklearn==0.0
    - scikit-learn==0.24.2
    - statsmodels==0.13.2
    - lxml==5.2.2
    - torch==1.9.0+cu111
    - torchaudio==0.9.0
    - torchvision==0.10.0+cu111
    - "-f https://download.pytorch.org/whl/torch_stable.html"
    - xgboost==1.3.3
    - pyDOE==0.3.8
    - pytest==6.2.4
    - POAP==0.1.26
    - subprocess32==3.5.4
